// app/components-react/windows/settings/HotkeyGroup.tsx
import React, { useState } from 'react';
import Animate from 'rc-animate';
import cx from 'classnames';
import { IHotkey } from 'services/hotkeys';
import Hotkey from './Hotkey';

interface CommonProps {
  title: string | null;
}

interface HotkeyGroupProps extends CommonProps {
  hotkeys: IHotkey[];
  isSearch: boolean;
}

interface HeaderProps extends CommonProps {
  isCollapsible: boolean;
  collapsed: boolean;
  handleClick: () => void;
}

const getHotkeyUniqueId = (hotkey: IHotkey) => {
  return hotkey.actionName + hotkey.sceneId + hotkey.sceneItemId + hotkey.sourceId;
};

function Header({ title, isCollapsible, collapsed, handleClick }: HeaderProps) {
  return title ? (
    <h2 className="section-title section-title--dropdown" onClick={handleClick}>
      {isCollapsible && collapsed ? <i className="fa fa-plus section-title__icon" /> : null}
      {isCollapsible && !collapsed ? <i className="fa fa-minus section-title__icon" /> : null}
      {title}
    </h2>
  ) : null;
}

export default function HotkeyGroup(props: HotkeyGroupProps) {
  const { hotkeys, title, isSearch } = props;
  const [collapsed, setCollapsed] = useState(true);
  const isCollapsible = !!(title && !isSearch);

  const toggleCollapsed = () => {
    setCollapsed(collapsed => !collapsed);
  };

  const headerProps = { title, isCollapsible, collapsed, handleClick: toggleCollapsed };

  return (
    <div className="section">
      <Header {...headerProps} />
      {/* TODO: not sure whether this matches Vue's expand */}
      <Animate transitionName="slidedown">
        {(!isCollapsible || !collapsed) && (
          <div className={cx({ 'section-content--opened': !!title }, 'section-content')}>
            {hotkeys.map(hotkey => (
              <div key={getHotkeyUniqueId(hotkey)}>
                <Hotkey hotkey={hotkey} />
              </div>
            ))}
          </div>
        )}
      </Animate>
    </div>
  );
}

// app/components/windows/settings/HotkeyGroup.tsx
import { Component } from 'vue-property-decorator';
import Hotkey from 'components/shared/Hotkey.vue';
import { IHotkey } from 'services/hotkeys';
import cx from 'classnames';
import TsxComponent, { createProps } from 'components/tsx-component';

class HotkeyGroupProps {
  hotkeys: IHotkey[] = [];
  title: string = null;
  isSearch: boolean = false;
}

@Component({ props: createProps(HotkeyGroupProps) })
export default class HotkeyGroup extends TsxComponent<HotkeyGroupProps> {
  collapsed = true;

  get header() {
    return this.props.title ? (
      <h2
        class="section-title section-title--dropdown"
        onClick={() => (this.collapsed = !this.collapsed)}
      >
        {this.isCollapsible && this.collapsed ? <i class="fa fa-plus section-title__icon" /> : null}
        {this.isCollapsible && !this.collapsed ? (
          <i class="fa fa-minus section-title__icon" />
        ) : null}
        {this.props.title}
      </h2>
    ) : null;
  }

  get isCollapsible() {
    return this.props.title && !this.props.isSearch;
  }

  render() {
    return (
      <div class="section">
        {this.header}
        <transition name="expand">
          {(!this.isCollapsible || !this.collapsed) && (
            <div class={cx({ 'section-content--opened': !!this.props.title }, 'section-content')}>
              {this.props.hotkeys.map(hotkey => (
                <div
                  key={hotkey.actionName + hotkey.sceneId + hotkey.sceneItemId + hotkey.sourceId}
                >
                  <Hotkey hotkey={hotkey} />
                </div>
              ))}
            </div>
          )}
        </transition>
      </div>
    );
  }
}
