// app/components-react/windows/scene-transitions/ConnectionSettings.tsx
import { useVuex } from 'components-react/hooks';
import { Services } from 'components-react/service-provider';
import FormFactory from 'components-react/shared/inputs/FormFactory';
import React from 'react';
import { $t } from 'services/i18n';
import { metadata } from '../../shared/inputs/metadata';

export default function SceneTransitions(p: { connectionId: string }) {
  const { TransitionsService, ScenesService, EditorCommandsService } = Services;

  const { connection, transitionOptions } = useVuex(() => ({
    connection: TransitionsService.state.connections.find(conn => conn.id === p.connectionId),
    transitionOptions: TransitionsService.state.transitions.map(transition => ({
      label: transition.name,
      value: transition.id,
    })),
  }));

  if (!connection) return <></>;

  const values = {
    fromSceneId: connection.fromSceneId,
    transitionId: connection.transitionId,
    toSceneId: connection.toSceneId,
  };

  const sceneOptions = [
    { label: $t('All'), value: 'ALL' },
    ...ScenesService.views.scenes.map(scene => ({ label: scene.name, value: scene.id })),
  ];

  const meta = {
    fromSceneId: metadata.list({ label: $t('Beginning Scene'), options: sceneOptions }),
    transitionId: metadata.list({ label: $t('Scene Transition'), options: transitionOptions }),
    toSceneId: metadata.list({ label: $t('Ending Scene'), options: sceneOptions }),
  };

  function handleInput(key: string) {
    return (value: string) =>
      EditorCommandsService.actions.executeCommand('EditConnectionCommand', p.connectionId, {
        [key]: value,
      });
  }

  return (
    <FormFactory
      values={values}
      metadata={meta}
      onChange={handleInput}
      formOptions={{ layout: 'vertical' }}
    />
  );
}

// app/components/ConnectionSettings.tsx
import TsxComponent from 'components/tsx-component';
import { Component, Prop } from 'vue-property-decorator';
import { Inject } from 'services/core/injector';
import { TransitionsService } from 'services/transitions';
import { ScenesService } from 'services/scenes';
import VFormGroup from 'components/shared/inputs/VFormGroup.vue';
import { $t } from 'services/i18n';
import { EditorCommandsService } from 'services/editor-commands';
import { metadata } from './shared/inputs';

@Component({})
export default class SceneTransitions extends TsxComponent<{ connectionId: string }> {
  @Inject() transitionsService: TransitionsService;
  @Inject() scenesService: ScenesService;
  @Inject() private editorCommandsService: EditorCommandsService;

  @Prop() connectionId: string;

  get fromSceneModel(): string {
    return this.connection.fromSceneId;
  }

  setFromSceneModel(value: string) {
    this.editorCommandsService.executeCommand('EditConnectionCommand', this.connectionId, {
      fromSceneId: value,
    });
  }

  get toSceneModel(): string {
    return this.connection.toSceneId;
  }

  setToSceneModel(value: string) {
    this.editorCommandsService.executeCommand('EditConnectionCommand', this.connectionId, {
      toSceneId: value,
    });
  }

  get transitionModel(): string {
    return this.connection.transitionId;
  }

  setTransitionModel(value: string) {
    this.editorCommandsService.executeCommand('EditConnectionCommand', this.connectionId, {
      transitionId: value,
    });
  }

  get connection() {
    return this.transitionsService.state.connections.find(conn => conn.id === this.connectionId);
  }

  get sceneOptions() {
    return [
      { title: $t('All'), value: 'ALL' },
      ...this.scenesService.views.scenes.map(scene => ({
        title: scene.name,
        value: scene.id,
      })),
    ];
  }

  get transitionOptions() {
    return this.transitionsService.state.transitions.map(transition => ({
      title: transition.name,
      value: transition.id,
    }));
  }

  render(h: Function) {
    return (
      <div>
        <VFormGroup
          value={this.fromSceneModel}
          onInput={this.setFromSceneModel}
          metadata={metadata.list({
            title: $t('Beginning Scene'),
            name: 'from',
            options: this.sceneOptions,
          })}
        />
        <VFormGroup
          value={this.transitionModel}
          onInput={this.setTransitionModel}
          metadata={metadata.list({
            title: $t('Scene Transition'),
            name: 'transition',
            options: this.transitionOptions,
          })}
        />
        <VFormGroup
          value={this.toSceneModel}
          onInput={this.setToSceneModel}
          metadata={metadata.list({
            title: $t('Ending Scene'),
            name: 'to',
            options: this.sceneOptions,
          })}
        />
      </div>
    );
  }
}
