// app/components-react/shared/PerformanceMetrics.tsx
import React from 'react';
import { Tooltip } from 'antd';
import cx from 'classnames';
import { useVuex } from '../hooks';
import { Services } from '../service-provider';
import cloneDeep from 'lodash/cloneDeep';
import styles from './PerformanceMetrics.m.less';
import { $t } from '../../services/i18n';

type TPerformanceMetricsMode = 'full' | 'limited';

export default function PerformanceMetrics(props: {
  mode: TPerformanceMetricsMode;
  className?: string;
}) {
  const { CustomizationService, PerformanceService } = Services;

  const v = useVuex(
    () => ({
      pinnedStats: CustomizationService.views.pinnedStatistics,
      cpuPercent: PerformanceService.views.cpuPercent,
      frameRate: PerformanceService.views.frameRate,
      droppedFrames: PerformanceService.views.droppedFrames,
      percentDropped: PerformanceService.views.percentDropped,
      bandwidth: PerformanceService.views.bandwidth,
    }),
    false,
  );

  function showAttribute(attribute: string) {
    return props.mode === 'full' || v.pinnedStats[attribute];
  }

  function pinTooltip(stat: string) {
    return props.mode === 'full' ? $t('Click to add %{stat} info to your footer', { stat }) : '';
  }

  function classForStat(stat: string) {
    if (props.mode === 'limited') return '';
    return `clickable ${v.pinnedStats[stat] ? 'active' : ''}`;
  }

  function updatePinnedStats(key: string, value: boolean) {
    if (props.mode === 'limited') return;
    const newStats = cloneDeep(v.pinnedStats);
    newStats[key] = value;
    CustomizationService.actions.setPinnedStatistics(newStats);
  }

  const metadata = {
    cpu: { value: `${v.cpuPercent}%`, label: $t('CPU'), icon: 'icon-cpu' },
    fps: { value: v.frameRate, label: 'FPS', icon: 'icon-fps' },
    droppedFrames: {
      value: `${v.droppedFrames} (${v.percentDropped}%)`,
      label: $t('Dropped Frames'),
      icon: 'icon-dropped-frames',
    },
    bandwidth: { value: v.bandwidth, label: 'kb/s', icon: 'icon-bitrate' },
  };

  const shownCells = ['cpu', 'fps', 'droppedFrames', 'bandwidth'].filter((val: string) =>
    showAttribute(val),
  );

  function showLabel(attribute: string) {
    if (attribute !== 'droppedFrames') return true;
    return props.mode === 'full';
  }

  return (
    <div
      className={cx(
        styles.performanceMetrics,
        'performance-metrics',
        'flex flex--center',
        props.className,
      )}
    >
      {shownCells.map(attribute => {
        const data = metadata[attribute];
        return (
          <Tooltip placement="bottom" title={pinTooltip(data.label)} key={attribute}>
            <span
              className={cx(
                styles.performanceMetricWrapper,
                classForStat(attribute),
                'performance-metric-wrapper',
              )}
              onClick={() => updatePinnedStats(attribute, !v.pinnedStats[attribute])}
            >
              <i className={cx(styles.performanceMetricIcon, data.icon)} />
              <span className={styles.performanceMetric}>
                <span className={styles.performanceMetricValue}>{data.value}</span>
                {showLabel(attribute) && (
                  <span className={styles.performanceMetricLabel}> {data.label}</span>
                )}
              </span>
            </span>
          </Tooltip>
        );
      })}
    </div>
  );
}

// app/components/PerformanceMetrics.vue
<template>
<div class="performance-metrics flex flex--center">
  <span
    :class="[
      'performance-metric-wrapper', classForStat('cpu')]"
    @click="() => (updatePinnedStats('cpu', !pinnedStats.cpu))"
    v-tooltip="pinTooltip('CPU')"
    v-if="showCPU"
  >
    <i class="performance-metric-icon icon-cpu"></i>
    <span class="performance-metric">
      <span class="performance-metric__value">{{ cpuPercent }}%</span>
      <span class="performance-metric__label">{{ $t('CPU') }}</span>
    </span>
  </span>

  <span
    :class="['performance-metric-wrapper', classForStat('fps')]"
    @click="() => (updatePinnedStats('fps', !pinnedStats.fps))"
    v-tooltip="pinTooltip('FPS')"
    v-if="showFPS"
  >
    <i class="performance-metric-icon icon-fps"></i>
    <span class="performance-metric">
      <span class="performance-metric__value">{{ frameRate }}</span>
      <span class="performance-metric__label">FPS</span>
    </span>
  </span>

  <span
    :class="['performance-metric-wrapper', classForStat('droppedFrames')]"
    @click="() => (updatePinnedStats('droppedFrames', !pinnedStats.droppedFrames))"
    v-tooltip="pinTooltip('dropped frames')"
    v-if="showDroppedFrames"
  >
    <i class="performance-metric-icon icon-dropped-frames"></i>
    <span class="performance-metric">
      <span class="performance-metric__value">{{ droppedFrames }} ({{ percentDropped }}%)</span>
      <span v-if="mode === 'full'" class="performance-metric__label">{{ $t('Dropped Frames') }}</span>
    </span>
  </span>

  <span
    :class="['performance-metric-wrapper', classForStat('bandwidth')]"
    @click="() => (updatePinnedStats('bandwidth', !pinnedStats.bandwidth))"
    v-tooltip="pinTooltip('bandwidth')"
    v-if="showBandwidth"
  >
    <i class="performance-metric-icon icon-bitrate"></i>
    <span class="performance-metric">
      <span class="performance-metric__value">{{ bandwidth }}</span>
      <span class="performance-metric__label">kb/s</span>
    </span>
  </span>
</div>
</template>

<script lang="ts" src="./PerformanceMetrics.vue.ts"></script>

<style lang="less" scoped>
@import '../styles/index';

.performance-metrics {
  background: var(--background);
  height: calc(100% - 30px);
}

.performance-metric-wrapper {
  .padding-right();

  color: var(--paragraph);
  white-space: nowrap;
  display: flex;
  align-items: center;

  &::before {
    .padding-right();

    content: '|';
    opacity: 0.5;
  }
}

.performance-metric-wrapper.active {
  background: var(--input-border);
}

.performance-metric-wrapper.clickable {
  cursor: pointer;
}

.performance-metric {
  vertical-align: middle;
}

.performance-metric-icon {
  .margin-right();

  height: 14px;
  width: auto;
  vertical-align: text-top;

  @media (max-width: 1200px) {
    display: none;
  }

  @media (max-width: 1300px) {
    height: 12px;
  }
}

.performance-metric__value {
  .weight(@medium);
}
</style>
