// app/components-react/root/StudioFooter.tsx
import React, { useState, useEffect } from 'react';
import cx from 'classnames';
import { EStreamQuality } from '../../services/performance';
import { EStreamingState, EReplayBufferState } from '../../services/streaming';
import { Services } from '../service-provider';
import { $t } from '../../services/i18n';
import { useRenderInterval, useVuex } from '../hooks';
import styles from './StudioFooter.m.less';
import PerformanceMetrics from '../shared/PerformanceMetrics';
import TestWidgets from './TestWidgets';
import StartStreamingButton from './StartStreamingButton';
import NotificationsArea from './NotificationsArea';
import { Tooltip } from 'antd';

export default function StudioFooterComponent(p: { locked?: boolean }) {
  const {
    StreamingService,
    UserService,
    WindowsService,
    SettingsService,
    PerformanceService,
    YoutubeService,
    UsageStatisticsService,
  } = Services;

  const [recordingTime, setRecordingTime] = useState('');

  const {
    streamingStatus,
    platform,
    streamQuality,
    isRecording,
    isLoggedIn,
    canSchedule,
    replayBufferEnabled,
    replayBufferOffline,
    replayBufferStopping,
    replayBufferSaving,
  } = useVuex(() => ({
    streamingStatus: StreamingService.views.streamingStatus,
    platform: UserService.views.platform?.type,
    streamQuality: PerformanceService.views.streamQuality,
    isRecording: StreamingService.views.isRecording,
    isLoggedIn: UserService.views.isLoggedIn,
    canSchedule: StreamingService.views.supports('stream-schedule'),
    replayBufferEnabled: SettingsService.views.values.Output.RecRB,
    replayBufferOffline: StreamingService.state.replayBufferStatus === EReplayBufferState.Offline,
    replayBufferStopping: StreamingService.state.replayBufferStatus === EReplayBufferState.Stopping,
    replayBufferSaving: StreamingService.state.replayBufferStatus === EReplayBufferState.Saving,
  }));

  useRenderInterval(() => {
    if (!isRecording) return;
    setRecordingTime(StreamingService.formattedDurationInCurrentRecordingState);
  }, 1000);

  useEffect(confirmYoutubeEnabled, [platform]);

  const youtubeEnabled = platform === 'youtube' ? YoutubeService.state.liveStreamingEnabled : true;

  function toggleRecording() {
    StreamingService.toggleRecording();
  }

  function performanceIconClassName() {
    if (!streamingStatus || streamingStatus === EStreamingState.Offline) {
      return '';
    }

    if (streamingStatus === EStreamingState.Reconnecting || streamQuality === EStreamQuality.POOR) {
      return 'warning';
    }

    if (streamQuality === EStreamQuality.FAIR) {
      return 'info';
    }

    return 'success';
  }

  function confirmYoutubeEnabled() {
    if (platform === 'youtube') {
      YoutubeService.prepopulateInfo();
    }
  }

  function openYoutubeEnable() {
    YoutubeService.actions.openYoutubeEnable();
  }

  function openScheduleStream() {
    WindowsService.showWindow({
      componentName: 'ScheduleStreamWindow',
      title: $t('Schedule Stream'),
      size: { width: 800, height: 670 },
    });
  }

  function openMetricsWindow() {
    WindowsService.showWindow({
      componentName: 'AdvancedStatistics',
      title: $t('Performance Metrics'),
      size: { width: 700, height: 550 },
      resizable: true,
      maximizable: false,
      minWidth: 500,
      minHeight: 400,
    });
    UsageStatisticsService.recordFeatureUsage('PerformanceStatistics');
  }

  function toggleReplayBuffer() {
    if (StreamingService.state.replayBufferStatus === EReplayBufferState.Offline) {
      StreamingService.startReplayBuffer();
    } else {
      StreamingService.stopReplayBuffer();
    }
  }

  function saveReplay() {
    StreamingService.saveReplay();
  }

  return (
    <div className={styles.footer}>
      <div className="flex flex--center flex--grow flex--justify-start">
        {isLoggedIn && youtubeEnabled && (
          <div className={styles.errorWrapper}>
            <div className={styles.platformError}>
              <i className="fa fa-exclamation-triangle" />
              <span>{$t('YouTube account not enabled for live streaming')}</span>
              <button className="button alert-button" onClick={openYoutubeEnable}>
                {$t('Fix')}
              </button>
              <button className="button alert-button" onClick={confirmYoutubeEnabled}>
                {$t("I'm set up")}
              </button>
            </div>
          </div>
        )}
        <Tooltip placement="left" title={$t('Open Performance Window')}>
          <i
            className={cx('icon-leaderboard-4', 'metrics-icon', performanceIconClassName())}
            onClick={openMetricsWindow}
          />
        </Tooltip>
        <PerformanceMetrics mode="limited" className="performance-metrics" />
        <NotificationsArea />
      </div>

      <div className={styles.navRight}>
        <div className={styles.navItem}>{isLoggedIn && <TestWidgets />}</div>
        {isRecording && (
          <div className={cx(styles.navItem, styles.recordTime)}>{recordingTime}</div>
        )}
        <div className={styles.navItem}>
          <button
            disabled={p.locked}
            className={cx(styles.recordButton, { [styles.active]: isRecording })}
            onClick={toggleRecording}
          >
            <span>REC</span>
          </button>
        </div>
        {replayBufferEnabled && replayBufferOffline && (
          <div className={styles.navItem}>
            <Tooltip placement="left" title={$t('Start Replay Buffer')}>
              <button className="circle-button" onClick={toggleReplayBuffer}>
                <i className="icon-replay-buffer" />
              </button>
            </Tooltip>
          </div>
        )}
        {!replayBufferOffline && (
          <div className={cx(styles.navItem, styles.replayButtonGroup)}>
            <Tooltip placement="left" title={$t('Stop')}>
              <button
                className={cx('circle-button', styles.leftReplay, 'button--soft-warning')}
                onClick={toggleReplayBuffer}
              >
                <i className="fa fa-stop" />
              </button>
            </Tooltip>
            <Tooltip placement="left" title={$t('Save Replay')}>
              <button
                className={cx('circle-button', styles.rightReplay)}
                onClick={saveReplay}
                disabled={replayBufferSaving || replayBufferStopping}
              >
                <i className="icon-save" />
              </button>
            </Tooltip>
          </div>
        )}
        {canSchedule && (
          <div className={styles.navItem}>
            <Tooltip placement="left" title={$t('Schedule Stream')}>
              <button className="circle-button" onClick={openScheduleStream}>
                <i className="icon-date" />
              </button>
            </Tooltip>
          </div>
        )}
        <div className={styles.navItem}>
          <StartStreamingButton disabled={p.locked} />
        </div>
      </div>
    </div>
  );
}

// app/components/StudioFooter.vue
<template>
<div class="footer">
  <div class="flex flex--center flex--grow flex--justify-start">
    <div class="error-wrapper" v-if="loggedIn && !youtubeEnabled">
      <div class="platform-error">
        <i class="fa fa-exclamation-triangle" />
        <span>{{ $t('YouTube account not enabled for live streaming') }}</span>
        <button class="button alert-button" @click="openYoutubeEnable">{{ $t('Fix') }}</button>
        <button class="button alert-button" @click="confirmYoutubeEnabled">{{ $t('I\'m set up') }}</button>
      </div>
    </div>
    <i
      v-bind:class="['icon-leaderboard-4', 'metrics-icon', performanceIconClassName]"
      @click="openMetricsWindow"
    />
    <performance-metrics mode="limited" class="performance-metrics" />
    <global-sync-status v-if="loggedIn && !mediaBackupOptOut" />
    <notifications-area class="notifications-area flex--grow"/>
    <!-- <transition name="slide">
      <performance-metrics v-if="metricsShown" class="performance-metrics" />
    </transition> -->
  </div>

  <div class="nav-right">
    <div class="nav-item">
      <test-widgets v-if="loggedIn" />
    </div>
    <div v-if="streamingService.isRecording" class="nav-item record-time">
      {{ recordingTime }}
    </div>
    <div class="nav-item">
      <button
        :disabled="locked"
        class="record-button"
        @click="toggleRecording"
        :class="{ active: streamingService.isRecording }">
        <span>REC</span>
      </button>
    </div>
    <div class="nav-item" v-if="replayBufferEnabled && replayBufferOffline">
      <button class="circle-button" @click="toggleReplayBuffer" v-tooltip.left="$t('Start Replay Buffer')"><i class="icon-replay-buffer" /></button>
    </div>
    <div class="nav-item replay-button-group" v-if="!replayBufferOffline">
      <button class="circle-button left-replay button--soft-warning" @click="toggleReplayBuffer" v-tooltip.left="$t('Stop')"><i class="fa fa-stop" /></button>
      <button class="circle-button right-replay" @click="saveReplay" :disabled="replayBufferSaving || replayBufferStopping" v-tooltip.left="$t('Save Replay')">
        <i class="icon-save" />
      </button>
    </div>
    <div class="nav-item" v-if="canSchedule">
      <button class="circle-button" @click="openScheduleStream" v-tooltip.left="$t('Schedule Stream')"><i class="icon-date" /></button>
    </div>
    <div class="nav-item">
      <start-streaming-button :disabled="locked" />
    </div>
  </div>
</div>
</template>

<script lang="ts" src="./StudioFooter.vue.ts"></script>

<style lang="less" scoped>
@import '../styles/index';

.footer {
  .padding-h-sides(2);
  .padding-v-sides();

  display: flex;
  justify-content: space-between;
  flex-direction: row;
  align-items: center;
  position: relative;
  background-color: var(--section);
  max-width: none;
  flex: 0 0 auto;
}

.nav-right {
  display: flex;
  align-items: center;
}

.nav-item {
  .margin-left(2);
}

.error-wrapper {
  background-color: var(--section);
  position: absolute;
  z-index: 2;
}

.platform-error {
  background: var(--warning-bg);
  padding: 5px;
  .radius();

  i {
    margin-left: 5px;
    color: var(--warning);
  }

  span {
    padding-left: 5px;
    margin-right: 10px;
    color: var(--warning);
  }

  .alert-button {
    height: 18px;
    line-height: 12px;
    background: rgba(251, 72, 76, 0.36);
    margin: 0 5px;
    padding: 0 8px;
    font-size: 10px;
  }
}

.metrics-icon {
  padding-right: 12px;

  &:hover {
    cursor: pointer;
  }
}

.warning {
  color: var(--warning);
}

.info {
  color: var(--info-dark);
}

.success {
  color: var(--teal);
}

.record-button {
  .transition();
  .weight(@bold);

  position: relative;
  width: 30px;
  height: 30px;
  background-color: var(--button);
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 100%;
  box-sizing: content-box;
  letter-spacing: 0.2px;

  span {
    font-size: 10px;
    color: var(--warning);
  }

  &:hover {
    background-color: var(--button-hover);
  }

  &.active {
    animation: pulse 2.5s linear infinite;
    background-color: var(--warning);

    span {
      color: var(--white);
    }
  }

  &:focus {
    outline: none;
  }
}

.record-time {
  color: var(--warning);
}

@keyframes pulse {
  0% {
    box-shadow: 0 0 2px 0 rgba(252, 62, 63, 0.6);
  }

  70% {
    box-shadow: 0 0 2px 4px rgba(252, 62, 63, 0.6);
  }

  100% {
    box-shadow: 0 0 2px 4px rgba(252, 62, 63, 0);
  }
}

.replay-button-group {
  font-size: 0;
  white-space: nowrap;
  display: flex;

  > button {
    font-size: 12px;
  }

  > .left-replay {
    border-radius: 100% 0 0 100%;
  }

  > .right-replay {
    border-radius: 0 100% 100% 0;
  }
}

.performance-metrics {
  position: relative;
  display: inline-flex;
  background: var(--section) !important;
}
</style>
