// app/components/windows/AdvancedAudio.tsx
import Vue from 'vue';
import { Component } from 'vue-property-decorator';
import { Inject } from '../../services/core/injector';
import { WindowsService } from '../../services/windows';
import { AudioService, AudioSource } from '../../services/audio';
import { propertyComponentForType } from 'components/obs/inputs/Components';
import ModalLayout from '../ModalLayout.vue';
import { TObsValue } from 'components/obs/inputs/ObsInput';
import { EditorCommandsService } from 'services/editor-commands';
import { $t } from 'services/i18n';
import styles from './AdvancedAudio.m.less';

@Component({
  components: { ModalLayout },
})
export default class AdvancedAudio extends Vue {
  @Inject() audioService: AudioService;
  @Inject() windowsService: WindowsService;
  @Inject() editorCommandsService: EditorCommandsService;

  get audioSources() {
    return this.audioService.views.sourcesForCurrentScene;
  }

  onInputHandler(audioSource: AudioSource, name: string, value: TObsValue) {
    if (name === 'deflection') {
      this.editorCommandsService.executeCommand(
        'SetDeflectionCommand',
        audioSource.sourceId,
        (value as number) / 100,
      );
    } else {
      this.editorCommandsService.executeCommand('SetAudioSettingsCommand', audioSource.sourceId, {
        [name]: value,
      });
    }
  }

  get tableHeaders() {
    return (
      <thead>
        <tr>
          <th class={styles.audioSourceName}>{$t('Name')}</th>
          <th>{$t('Volume ( % )')}</th>
          <th>{$t('Hide in Mixer')}</th>
          <th>{$t('Downmix to Mono')}</th>
          <th>{$t('Sync Offset ( ms )')}</th>
          <th>{$t('Audio Monitoring')}</th>
          <th>{$t('Tracks')}</th>
        </tr>
      </thead>
    );
  }

  render() {
    return (
      <ModalLayout showControls={false}>
        <form slot="content">
          <table style={{ width: '100%' }}>
            {this.tableHeaders}

            {this.audioSources.map(audioSource => (
              <tr key={audioSource.name} name={audioSource.name} class={styles.audioSettingsRow}>
                <td class={styles.nameCell}>
                  <div class={styles.audioSourceName}>{audioSource.name}</div>
                </td>
                {audioSource.getSettingsForm().map(formInput => {
                  const Component = propertyComponentForType(formInput.type);
                  return (
                    <td
                      key={`${audioSource.name}${formInput.name}`}
                      class={styles['column-' + formInput.name]}
                    >
                      <div class={styles.advancedAudioInput}>
                        <Component
                          value={formInput}
                          onInput={(value: { value: TObsValue }) =>
                            this.onInputHandler(audioSource, formInput.name, value.value)
                          }
                        />
                      </div>
                    </td>
                  );
                })}
              </tr>
            ))}
          </table>
        </form>
      </ModalLayout>
    );
  }
}

// app/components-react/windows/AdvancedAudio.tsx
import React, { useState } from 'react';
import { Collapse } from 'antd';
import { ModalLayout } from 'components-react/shared/ModalLayout';
import {
  SliderInput,
  BoolButtonInput,
  ListInput,
  SwitchInput,
} from 'components-react/shared/inputs';
import Form from 'components-react/shared/inputs/Form';
import { TObsValue } from 'components/obs/inputs/ObsInput';
import { Services } from 'components-react/service-provider';
import { AudioSource } from 'services/audio';
import { $t } from 'services/i18n';
import styles from './AdvancedAudio.m.less';
import { useVuex } from 'components-react/hooks';

const { Panel } = Collapse;

export default function AdvancedAudio() {
  const { AudioService, EditorCommandsService, WindowsService } = Services;
  const initialSource = WindowsService.getChildWindowQueryParams().sourceId || '';

  const [expandedSource, setExpandedSource] = useState(initialSource);

  const { audioSources } = useVuex(() => ({
    audioSources: AudioService.views.sourcesForCurrentScene,
  }));

  function onInputHandler(sourceId: string, name: string, value: TObsValue) {
    EditorCommandsService.executeCommand('SetAudioSettingsCommand', sourceId, {
      [name]: value,
    });
  }

  return (
    <ModalLayout hideFooter>
      <Collapse
        accordion
        activeKey={expandedSource}
        onChange={(key: string) => setExpandedSource(key)}
        expandIcon={({ isActive }) => <i className={isActive ? 'icon-subtract' : 'icon-add'} />}
      >
        {audioSources.map(audioSource => (
          <Panel key={audioSource.sourceId} header={<PanelHeader source={audioSource} />}>
            <Form>
              <ListInput label={$t('Device')} options={[]} />
              <SwitchInput label={$t('Use Device Timestamps')} />
              <SliderInput label={$t('Sync Offset')} hasNumberInput />
              <SwitchInput label={$t('Downmix to Mono')} />
              <ListInput label={$t('Monitoring')} options={[]} />
            </Form>
          </Panel>
        ))}
      </Collapse>
    </ModalLayout>
  );
}

function PanelHeader(p: { source: AudioSource }) {
  const { name, mixerHidden, muted, fader, sourceId } = p.source;
  const { EditorCommandsService } = Services;

  function onInputHandler(name: string) {
    return (value: TObsValue) => {
      if (name === 'deflection') {
        EditorCommandsService.executeCommand(
          'SetDeflectionCommand',
          sourceId,
          (value as number) / 100,
        );
      } else {
        EditorCommandsService.executeCommand('SetAudioSettingsCommand', sourceId, {
          [name]: value,
        });
      }
    };
  }

  return (
    <div className={styles.audioSettingsRow} onClick={(e: React.MouseEvent) => e.stopPropagation()}>
      <div className={styles.audioSourceName}>{name}</div>
      <i
        className={muted ? 'icon-mute' : 'icon-audio'}
        onClick={() => onInputHandler('muted')(!muted)}
      />
      <SliderInput
        style={{ width: '200px', marginBottom: 0 }}
        value={fader.deflection}
        hasNumberInput
        onInput={onInputHandler('deflection')}
      />
      <i
        className={mixerHidden ? 'icon-hide' : 'icon-view'}
        onClick={() => onInputHandler('mixerHidden')(!mixerHidden)}
      />
      <div className={styles.audioSettingsTracks}>
        <div className={styles.trackLabel}>{$t('Stream Track')}</div>
        <BoolButtonInput label="1" />
      </div>
      <div className={styles.audioSettingsTracks}>
        <div className={styles.trackLabel}>{$t('Rec. Tracks')}</div>
        <BoolButtonInput label="5" />
        <BoolButtonInput label="6" />
      </div>
    </div>
  );
}
