// app/components-react/widgets/ChatBox.tsx
import React from 'react';
import { IWidgetCommonState, useWidget, WidgetModule } from './common/useWidget';
import { WidgetLayout } from './common/WidgetLayout';
import { $t } from '../../services/i18n';
import { metadata } from '../shared/inputs/metadata';
import FormFactory, { TInputValue } from 'components-react/shared/inputs/FormFactory';

interface IChatBoxSettings extends Dictionary<TInputValue> {
  theme: string;
  always_show_messages: boolean;
  message_hide_delay: number;
  message_show_delay: number;
  disable_message_animations: boolean;
  show_platform_icons: boolean;
  show_moderator_icons: boolean;
  show_subscriber_icons: boolean;
  show_turbo_icons: boolean;
  show_premium_icons: boolean;
  show_bits_icons: boolean;
  show_coin_icons: boolean;
  show_bttv_emotes: boolean;
  show_franker_emotes: boolean;
  show_7tv_emotes: boolean;
  text_color: string;
  text_size: number;
  background_color: string;
  hide_common_chat_bots: boolean;
  hide_commands: boolean;
  muted_chatters: string;
}

interface IChatBoxState extends IWidgetCommonState {
  data: {
    settings: IChatBoxSettings;
  };
}

export function ChatBox() {
  const { isLoading, settings, meta, updateSetting } = useChatBox();

  return (
    <WidgetLayout>
      {!isLoading && <FormFactory metadata={meta} values={settings} onChange={updateSetting} />}
    </WidgetLayout>
  );
}

export class ChatBoxModule extends WidgetModule<IChatBoxState> {
  get meta() {
    return {
      theme: metadata.list({
        label: $t('Theme'),
        options: [
          { label: 'Clean', value: 'clean' },
          { label: 'Boxed', value: 'boxed' },
          { label: 'Twitch', value: 'twitch' },
          { label: 'Old School', value: 'oldschool' },
          { label: 'Chunky', value: 'chunky' },
        ],
      }),
      always_show_messages: metadata.switch({ label: $t('Always Show Messages') }),
      message_hide_delay: metadata.seconds({
        label: $t('Hide Delay'),
        min: 0,
        max: 200000,
      }),
      message_show_delay: metadata.seconds({
        label: $t('Chat Delay'),
        min: 0,
        max: 6000,
      }),
      disable_message_animations: metadata.bool({ label: $t('Disable Message Animations') }),
      show_platform_icons: metadata.switch({ label: $t('Show Platform Icons') }),
      show_badges: {
        type: 'checkboxGroup',
        label: $t('Badges'),
        children: {
          show_moderator_icons: metadata.bool({ label: $t('Show Moderator Badges') }),
          show_subscriber_icons: metadata.bool({ label: $t('Show Subscriber Badges') }),
          show_turbo_icons: metadata.bool({ label: $t('Show Turbo Badges') }),
          show_premium_icons: metadata.bool({ label: $t('Show Twitch Prime Badges') }),
          show_bits_icons: metadata.bool({ label: $t('Show Bits Badges') }),
          show_coin_icons: metadata.bool({ label: $t('Show Top Coin Holder Badges') }),
        },
      },
      show_emotes: {
        type: 'checkboxGroup',
        label: $t('Extra Emotes'),
        children: {
          show_bttv_emotes: metadata.bool({ label: $t('Enable BetterTTV Emotes') }),
          show_franker_emotes: metadata.bool({ label: $t('Enable FrankerFaceZ Emotes') }),
          show_7tv_emotes: metadata.bool({ label: $t('Enable 7TV Emotes') }),
        },
      },
      text_color: metadata.color({
        label: $t('Text Color'),
        tooltip: $t('A hex code for the base text color.'),
      }),
      text_size: metadata.fontSize({ label: $t('Font Size'), min: 10, max: 80 }),
      background_color: metadata.color({
        label: $t('Background Color'),
        tooltip: $t(
          'A hex code for the widget background. This is for preview purposes only. It will not be shown in your stream.',
        ),
      }),
      hide_characters: {
        type: 'checkboxGroup',
        label: $t('Hide Characters'),
        children: {
          hide_common_chat_bots: metadata.bool({ label: $t('Hide Common Chat Bots') }),
          hide_commands: metadata.bool({ label: $t('Hide commands starting with `!`') }),
        },
      },
      muted_chatters: metadata.textarea({ label: $t('Muted Chatters') }),
    };
  }

  protected patchBeforeSend(settings: IChatBoxState) {
    // settings.
  }
}

function useChatBox() {
  return useWidget<ChatBoxModule>();
}

// app/components/widgets/ChatBox.vue
<template>
<widget-window v-if="wData" ref="layout" v-model="tabName">
  <div slot="settings" >

    <form-group title="Theme" type="list" v-model="wData.settings.theme" :metadata="metadata.theme"/>

    <form-group title="Badges">
      <bool-input title="Show Moderator Badges" v-model="wData.settings.show_moderator_icons"/>
      <bool-input title="Show Subscriber Badges" v-model="wData.settings.show_subscriber_icons"/>
      <bool-input title="Show Turbo Badges" v-model="wData.settings.show_turbo_icons"/>
      <bool-input title="Show Twitch Prime Badges" v-model="wData.settings.show_premium_icons"/>
      <bool-input title="Show Bits Badges" v-model="wData.settings.show_bits_icons"/>
      <bool-input title="Show Top Coin Holder Badges" v-model="wData.settings.show_coin_icons"/>
    </form-group>

    <form-group title="Extra Emotes">
      <bool-input title="Enable BetterTTV Emotes" v-model="wData.settings.show_bttv_emotes"/>
      <bool-input title="Enable FrankerFaceZ Emotes" v-model="wData.settings.show_franker_emotes"/>
      <bool-input title="Enable Supermegafan Emotes" v-model="wData.settings.show_smf_emotes"/>
    </form-group>

    <form-group title="Background Color" type="color" v-model="wData.settings.background_color" :metadata="{ tooltip: backgroundColorTooltip, description: backgroundColorDescription }" />
    <form-group title="Text Color" type="color" v-model="wData.settings.text_color" :metadata="{ tooltip: textColorTooltip }"/>
    <form-group title="Font Size" type="fontSize" v-model="wData.settings.text_size"/>

    <form-group title="Hide Message after">
      <bool-input title="Always Show Messages" v-model="wData.settings.always_show_messages"/>
      <slider-input v-model="wData.settings.message_hide_delay" :metadata="metadata.message_hide_delay"/>
    </form-group>

    <form-group title="Hide Characters">
      <bool-input title="Hide Common Chat Bots" v-model="wData.settings.hide_common_chat_bots"/>
      <bool-input title="Hide commands starting with `!`" v-model="wData.settings.hide_commands"/>
    </form-group>

    <form-group title="Muted Chatters" type="textArea" v-model="wData.settings.muted_chatters" />
  </div>


  <div slot="HTML" >
    <code-editor v-model="wData" :metadata="{ type: 'html' }"/>
  </div>

  <div slot="CSS" >
    <code-editor v-model="wData" :metadata="{ type: 'css' }"/>
  </div>

  <div slot="JS" >
    <code-editor v-model="wData" :metadata="{ type: 'js' }"/>
  </div>


</widget-window>

</template>

<script lang="ts" src="./ChatBox.vue.ts"></script>
