// app/components-react/editor/elements/Mixer.tsx
import React, { useRef, useMemo } from 'react';
import useBaseElement from './hooks';
import { Tooltip } from 'antd';
import { useVuex } from 'components-react/hooks';
import Scrollable from 'components-react/shared/Scrollable';
import GLVolmeters from './mixer/GLVolmeters';
import MixerItem from './mixer/MixerItem';
import { Services } from 'components-react/service-provider';
import { Menu } from 'util/menus/Menu';
import { $t } from 'services/i18n';

export default function Mixer() {
  const { EditorCommandsService, AudioService, CustomizationService } = Services;

  const containerRef = useRef<HTMLDivElement>(null);

  const { renderElement } = useBaseElement(<Element />, { x: 150, y: 120 }, containerRef.current);

  const needToRenderVolmeters: boolean = useMemo(() => {
    // render volmeters without hardware acceleration only if we don't have the webgl context
    const canvas = document.createElement('canvas');
    return !canvas.getContext('webgl');
  }, []);

  const { performanceMode, audioSources } = useVuex(() => ({
    performanceMode: CustomizationService.state.performanceMode,
    audioSources: AudioService.views.sourcesForCurrentScene.filter(
      source => !source.mixerHidden && source.isControlledViaObs,
    ),
  }));

  function showAdvancedSettings() {
    AudioService.actions.showAdvancedSettings();
  }

  function handleRightClick() {
    const menu = new Menu();
    menu.append({
      label: $t('Unhide All'),
      click: () => EditorCommandsService.actions.executeCommand('UnhideMixerSourcesCommand'),
    });
    menu.popup();
  }

  function Element() {
    return (
      <div onContextMenu={handleRightClick}>
        <div className="studio-controls-top">
          <Tooltip
            title={$t('Monitor audio levels. If the bars are moving you are outputting audio.')}
            placement="bottom"
          >
            <h2 className="studio-controls__label">{$t('Mixer')}</h2>
          </Tooltip>
          <Tooltip title={$t('Open advanced audio settings')} placement="left">
            <i
              className="icon-settings icon-button"
              role="show-advanced-audio"
              onClick={showAdvancedSettings}
            />
          </Tooltip>
        </div>
        <Scrollable className="studio-controls-selector mixer-panel">
          <div style={{ position: 'relative' }}>
            {audioSources.length !== 0 && !performanceMode && <GLVolmeters />}
            {audioSources.map(audioSource => (
              <MixerItem
                key={audioSource.sourceId}
                audioSourceId={audioSource.sourceId}
                volmetersEnabled={needToRenderVolmeters}
              />
            ))}
          </div>
        </Scrollable>
      </div>
    );
  }

  return (
    <div ref={containerRef} style={{ height: '100%' }}>
      {renderElement()}
    </div>
  );
}

// app/components/editor/elements/Mixer.tsx
import { Component } from 'vue-property-decorator';
import { AudioService } from 'services/audio';
import { Inject } from 'services/core/injector';
import MixerItem from 'components/MixerItem.vue';
import { $t } from 'services/i18n';
import { Menu } from 'util/menus/Menu';
import { EditorCommandsService } from 'services/editor-commands';
import BaseElement from './BaseElement';
import { CustomizationService } from 'services/customization';
import Scrollable from 'components/shared/Scrollable';
import { GLVolmeters } from '../../shared/ReactComponentList';

@Component({})
export default class Mixer extends BaseElement {
  @Inject() audioService: AudioService;
  @Inject() editorCommandsService: EditorCommandsService;
  @Inject() customizationService: CustomizationService;

  mins = { x: 150, y: 120 };

  private advancedSettingsTooltip = $t('Open advanced audio settings');
  private mixerTooltip = $t(
    'Monitor audio levels. If the bars are moving you are outputting audio.',
  );
  private needToRenderVolmeters: boolean = (() => {
    // render volmeters without hardware acceleration only if we don't have the webgl context
    const canvas = document.createElement('canvas');
    return !canvas.getContext('webgl');
  })();

  get performanceMode() {
    return this.customizationService.state.performanceMode;
  }

  showAdvancedSettings() {
    this.audioService.actions.showAdvancedSettings();
  }

  handleRightClick() {
    const menu = new Menu();
    menu.append({
      label: $t('Unhide All'),
      click: () => this.editorCommandsService.executeCommand('UnhideMixerSourcesCommand'),
    });
    menu.popup();
  }

  get audioSources() {
    return this.audioService.views.sourcesForCurrentScene.filter(source => {
      return !source.mixerHidden && source.isControlledViaObs;
    });
  }

  get element() {
    return (
      <div onContextmenu={() => this.handleRightClick()}>
        <div class="studio-controls-top">
          <h2
            class="studio-controls__label"
            v-tooltip={{ content: this.mixerTooltip, placement: 'bottom' }}
          >
            {$t('Mixer')}
          </h2>
          <div>
            <i
              class="icon-settings icon-button"
              role="show-advanced-audio"
              onClick={() => this.showAdvancedSettings()}
              v-tooltip={{ content: this.advancedSettingsTooltip, placement: 'left' }}
            />
          </div>
        </div>
        <Scrollable className="studio-controls-selector mixer-panel">
          <div style={{ position: 'relative' }}>
            {this.audioSources.length !== 0 && !this.performanceMode && (
              <GLVolmeters />
            )}
            {this.audioSources.map(audioSource => (
              <MixerItem
                audioSource={audioSource}
                key={audioSource.sourceId}
                volmetersEnabled={this.needToRenderVolmeters}
              />
            ))}
          </div>
        </Scrollable>
      </div>
    );
  }

  render() {
    return this.renderElement();
  }
}
