// app/components-react/pages/onboarding/ObsImport.tsx
import { useModule } from 'components-react/hooks/useModule';
import { alertAsync } from 'components-react/modals';
import { Services } from 'components-react/service-provider';
import AutoProgressBar from 'components-react/shared/AutoProgressBar';
import { ListInput } from 'components-react/shared/inputs';
import Form from 'components-react/shared/inputs/Form';
import KevinSvg from 'components-react/shared/KevinSvg';
import { mutation } from 'components-react/store';
import React from 'react';
import { $t } from 'services/i18n';
import commonStyles from './Common.m.less';
import styles from './ObsImport.m.less';
import { OnboardingModule } from './Onboarding';

export function ObsImport() {
  const { importing, percent } = useModule(ObsImportModule).select();

  return (
    <div style={{ width: '100%' }}>
      <h1 className={commonStyles.titleContainer}>
        {$t('Importing Your Existing Settings From OBS')}
      </h1>
      {!importing && <PreImport />}
      {importing && (
        <div className={styles.progressBar}>
          <AutoProgressBar percent={percent} timeTarget={10 * 1000} />
        </div>
      )}
      <div className={styles.textContainer}>
        <KevinSvg />
        <div>
          {$t(
            'While we import your settings and scenes from OBS Studio, check out these great features unique to Streamlabs',
          )}
        </div>
      </div>
      <FeatureCards />
    </div>
  );
}

function PreImport() {
  const { setProcessing, next } = useModule(OnboardingModule).select();
  const { profiles, selectedProfile, setSelectedProfile, startImport } = useModule(
    ObsImportModule,
  ).select();

  return (
    <div>
      {profiles.length > 1 && (
        <div style={{ width: 400, margin: 'auto', textAlign: 'center' }}>
          <span className={styles.profileSelectTitle}>{$t('Select an OBS profile to import')}</span>
          <Form layout="inline">
            <ListInput
              style={{ width: '100%' }}
              options={profiles.map(p => ({ label: p, value: p }))}
              value={selectedProfile}
              onChange={setSelectedProfile}
              allowClear={false}
            />
          </Form>
        </div>
      )}
      <button
        className={commonStyles.optionCard}
        style={{ margin: 'auto', marginTop: 24 }}
        onClick={() => {
          setProcessing(true);
          startImport()
            .then(() => {
              setProcessing(false);
              next();
            })
            .catch(() => {
              setProcessing(false);
              alertAsync(
                $t(
                  'Something went wrong while importing from OBS Studio. Please try again or skip to the next step.',
                ),
              );
            });
        }}
      >
        <h2>{$t('Start')}</h2>
      </button>
    </div>
  );
}

function FeatureCards() {
  const recommendedFeatures = ['appStore', 'gameOverlay'];
  const featuresMetadata = {
    appStore: {
      title: $t('App Store'),
      description: $t(
        'Check out 50+ amazing apps from independent developers, ranging from DMCA-compliant music ' +
          'to stunning overlays to more tools to engage with your community. Head over to the app store in the left ' +
          'navigation to browse our selection of free and paid apps.',
      ),
      image: 'app-store',
    },
    gameOverlay: {
      title: $t('In-game Overlay'),
      description: $t(
        'Only have one screen? Perfect! Enable our in-game overlay to make sure you catch every chat message and ' +
          'stream event that happens while you get your game on. You can enable this feature in the ‘Game Overlay’ ' +
          'tab of the settings menu.',
      ),
      image: 'game-overlay',
    },
  };

  return (
    <div className={styles.container}>
      {recommendedFeatures.map(feature => {
        const data = featuresMetadata[feature];
        return (
          <div className={styles.card} key={feature}>
            <div>
              <h3>{data.title}</h3>
              <div>{data.description}</div>
            </div>
            <img src={require(`../../../../media/images/onboarding/${data.image}.png`)} />
          </div>
        );
      })}
    </div>
  );
}

class ObsImportModule {
  state = {
    profiles: [] as string[],
    selectedProfile: '' as string | null,
    importing: false,
    percent: 0,
  };

  init() {
    // Intentionally synchronous
    const profiles = this.ObsImporterService.getProfiles();
    this.setProfiles(profiles);
    this.setSelectedProfile(profiles[0] ?? null);
  }

  get ObsImporterService() {
    return Services.ObsImporterService;
  }

  startImport() {
    if (this.state.importing) return Promise.resolve();
    if (!this.state.selectedProfile) return Promise.resolve();

    this.setImporting(true);

    return this.ObsImporterService.load(this.state.selectedProfile)
      .then(r => {
        this.setImporting(false);
        return r;
      })
      .catch(e => {
        this.setImporting(false);
        throw e;
      });
  }

  @mutation()
  setProfiles(profiles: string[]) {
    this.state.profiles = profiles;
  }

  @mutation()
  setSelectedProfile(profile: string) {
    this.state.selectedProfile = profile;
  }

  @mutation()
  setImporting(val: boolean) {
    this.state.importing = val;
  }

  @mutation()
  setPercent(val: number) {
    this.state.percent = val;
  }
}

// app/components/pages/onboarding-steps/ObsImport.tsx
import electron from 'electron';
import { Component } from 'vue-property-decorator';
import Multiselect from 'vue-multiselect';
import TsxComponent, { createProps } from 'components/tsx-component';
import KevinSvg from 'components/shared/KevinSvg';
import SmoothProgressBar from 'components/shared/SmoothProgressBar';
import { Inject } from 'services/core/injector';
import { ObsImporterService } from 'services/obs-importer';
import { ScenesService } from 'services/scenes';
import defer from 'lodash/defer';
import { $t } from 'services/i18n';
import commonStyles from './Common.m.less';
import styles from './ObsImport.m.less';

class ObsImportProps {
  continue: (bool: boolean) => void = () => {};
  setProcessing: (bool: boolean) => void = () => {};
}

@Component({ props: createProps(ObsImportProps) })
export default class ObsImport extends TsxComponent<ObsImportProps> {
  @Inject() obsImporterService!: ObsImporterService;
  @Inject() scenesService: ScenesService;

  progress = 0;
  importing = false;
  pathChosen = false;

  sceneCollections = this.obsImporterService.getSceneCollections();
  profiles = this.obsImporterService.getProfiles();
  selectedProfile = this.profiles[0] || null;

  startImport(forceStart?: boolean) {
    if (this.importing) return;
    this.pathChosen = true;
    if (this.profiles.length > 1 && !forceStart) return;

    this.importing = true;
    this.props.setProcessing(true);
    defer(async () => {
      try {
        await this.obsImporterService.load(this.selectedProfile);
        this.importing = false;
        this.progress = 1;
        this.props.setProcessing(false);
        this.props.continue(true);
      } catch (e: unknown) {
        this.$toasted.show($t('Something went wrong.'), {
          position: 'bottom-center',
          className: 'toast-alert',
          duration: 3000,
        });
        this.props.setProcessing(false);
        this.importing = false;
      }
    });
  }

  get recommendedFeatures() {
    return ['appStore', 'gameOverlay'];
  }

  get featuresMetadata() {
    return {
      appStore: {
        title: $t('App Store'),
        description: $t(
          'Check out 50+ amazing apps from independent developers, ranging from DMCA-compliant music ' +
            'to stunning overlays to more tools to engage with your community. Head over to the app store in the left ' +
            'navigation to browse our selection of free and paid apps.',
        ),
        image: 'app-store',
      },
      gameOverlay: {
        title: $t('In-game Overlay'),
        description: $t(
          'Only have one screen? Perfect! Enable our in-game overlay to make sure you catch every chat message and ' +
            'stream event that happens while you get your game on. You can enable this feature in the ‘Game Overlay’ ' +
            'tab of the settings menu.',
        ),
        image: 'game-overlay',
      },
    };
  }

  get featureCards() {
    return (
      <div class={styles.container}>
        {this.recommendedFeatures.map(feature => {
          const data = this.featuresMetadata[feature];
          return (
            <div class={styles.card}>
              <div>
                <h3>{data.title}</h3>
                <div>{data.description}</div>
              </div>
              <img src={require(`../../../../media/images/onboarding/${data.image}.png`)} />
            </div>
          );
        })}
      </div>
    );
  }

  get preImport() {
    if (this.importing) return null;
    return (
      <div>
        {this.profiles.length > 1 && (
          <div style="width: 400px; margin: auto;">
            <span class={styles.profileSelectTitle}>{$t('Select an OBS profile to import')}</span>
            <Multiselect
              class={styles.profileSelect}
              value={this.selectedProfile}
              onInput={(val: string) => (this.selectedProfile = val)}
              options={this.profiles}
              allowEmpty={false}
              showLabels={false}
            />
          </div>
        )}
        <button
          class={commonStyles.optionCard}
          style="margin: auto; margin-top: 24px;"
          onClick={() => this.startImport(true)}
        >
          <h2>{$t('Start')}</h2>
        </button>
      </div>
    );
  }

  render() {
    return (
      <div style="width: 100%;">
        <h1 class={commonStyles.titleContainer}>
          {$t('Importing Your Existing Settings From OBS')}
        </h1>
        {this.preImport}
        {this.importing && (
          <SmoothProgressBar
            value={this.progress}
            timeLimit={1000 * 10}
            class={styles.progressBar}
          />
        )}
        <div class={styles.textContainer}>
          <KevinSvg />
          <div>
            {$t(
              'While we import your settings and scenes from OBS Studio, check out these great features unique to Streamlabs OBS',
            )}
          </div>
        </div>
        {this.featureCards}
      </div>
    );
  }
}
