// app/components/shared/HelpTip.tsx
import cx from 'classnames';
import { Component } from 'vue-property-decorator';
import { Inject } from 'services/core/injector';
import { DismissablesService, EDismissable } from 'services/dismissables';
import TsxComponent, { createProps } from 'components/tsx-component';
import styles from './HelpTip.m.less';

class HelpTipProps {
  dismissableKey: EDismissable = null;
  position: {
    top?: string;
    left?: string;
    bottom?: string;
    right?: string;
  } = {};
  tipPosition?: 'left' | 'right' = 'left';
}

@Component({ props: createProps(HelpTipProps) })
export default class HelpTip extends TsxComponent<HelpTipProps> {
  @Inject() dismissablesService: DismissablesService;

  get shouldShow() {
    return this.dismissablesService.views.shouldShow(this.props.dismissableKey);
  }

  closeHelpTip() {
    this.dismissablesService.actions.dismiss(this.props.dismissableKey);
  }

  render() {
    return (
      this.shouldShow && (
        <div class={styles.helpTip} style={this.props.position}>
          <div
            class={cx(styles.helpTipArrow, {
              [styles.helpTipArrowRight]: this.props.tipPosition === 'right',
            })}
          />
          <i onClick={this.closeHelpTip} class={cx(styles.helpTipClose, 'icon-close')} />
          <div class={styles.helpTipTitle}>
            <i class="fa fa-info-circle" />
            {this.$slots.title}
          </div>
          <div class={styles.helpTipBody}>{this.$slots.content}</div>
        </div>
      )
    );
  }
}

// app/components-react/shared/HelpTip.tsx
import React from 'react';
import cx from 'classnames';
import { EDismissable } from 'services/dismissables';
import { Services } from 'components-react/service-provider';
import { useVuex } from 'components-react/hooks';
import styles from './HelpTip.m.less';

interface IHelpTipProps {
  title: string;
  dismissableKey: EDismissable;
  position: {
    top?: string;
    left?: string;
    bottom?: string;
    right?: string;
  };
  tipPosition?: 'left' | 'right';
}

export default function HelpTip(props: React.PropsWithChildren<IHelpTipProps>) {
  const p = { tipPosition: 'left', ...props };

  const { DismissablesService } = Services;

  const { shouldShow } = useVuex(() => ({
    shouldShow: DismissablesService.views.shouldShow(p.dismissableKey),
  }));

  function closeHelpTip() {
    DismissablesService.actions.dismiss(p.dismissableKey);
  }

  if (!shouldShow) return <></>;

  return (
    <div className={styles.helpTip} style={p.position}>
      <div
        className={cx(styles.helpTipArrow, {
          [styles.helpTipArrowRight]: p.tipPosition === 'right',
        })}
      />
      <i onClick={closeHelpTip} className={cx(styles.helpTipClose, 'icon-close')} />
      <div className={styles.helpTipTitle}>
        <i className="fa fa-info-circle" />
        {p.title}
      </div>
      <div className={styles.helpTipBody}>{p.children}</div>
    </div>
  );
}
