// app/components/shared/Hotkey.vue
<template>
<div class="Hotkey">
  <div class="Hotkey-description">
    {{ description }}
  </div>
  <div class="Hotkey-bindings">
    <transition-group name="bindings" tag="div">
      <div v-for="(binding, index) in bindings" :key="binding.key">
        <input
          type="text"
          class="Hotkey-input"
          :value="binding.binding"
          @keydown="e => handleKeydown(e, index)"/>
        <i
          class="Hotkey-control fa fa-plus"
          @click="addBinding(index)"/>
        <i
          class="Hotkey-control fa fa-minus"
          @click="removeBinding(index)"/>
      </div>
    </transition-group>
  </div>
</div>
</template>

<script>
import Vue from 'vue';
import { Component } from 'vue-property-decorator';
import { compact } from 'lodash';

@Component({
  props: ['hotkey']
})
export default class Hotkey extends Vue {

  data() {
    let bindings;

    if (this.hotkey.accelerators.size === 0) {
      bindings = [this.createBindingWithKey('')];
    } else {
      bindings = Array.from(this.hotkey.accelerators.values()).map(binding => {
        return this.createBindingWithKey(binding);
      });
    }

    return {
      description: this.hotkey.description,
      bindings
    };
  }

  handleKeydown(event, index) {
    if (this.isModifierPress(event)) return;

    const keys = [];

    keys.push(this.getModifier(event));
    keys.push(event.key);

    const accelerator = compact(keys).join('+');
    const binding = this.bindings[index];

    binding.binding = accelerator;

    this.setBindings();
  }

  getModifier(event) {
    if (event.altKey) return 'Alt';
    if (event.ctrlKey) return 'Ctrl';
    if (event.metaKey) return 'Super';
    if (event.shiftKey) return 'Shift';

    return '';
  }

  isModifierPress(event) {
    return (event.key === 'Control') ||
      (event.key === 'Alt') ||
      (event.key === 'Meta') ||
      (event.key === 'Shift');
  }

  // Adds a new blank binding
  addBinding(index) {
    this.bindings.splice(index + 1, 0, this.createBindingWithKey(''));
  }

  removeBinding(index) {
    // If this is the last binding, replace it with an
    // empty binding instead.
    if (this.bindings.length === 1) {
      this.bindings[0].binding = '';
      return;
    }

    this.bindings.splice(index, 1);
    this.setBindings();
  }

  // This is kind of weird, but the key attribute allows
  // us to uniquely identify that binding in the DOM,
  // which allows CSS animations to work properly.
  createBindingWithKey(binding) {
    return {
      binding,
      key: Math.random().toString(36).substring(2, 15)
    };
  }

  // Sets the bindings on the hotkey object
  setBindings() {
    const set = new Set();

    this.bindings.forEach(binding => {
      if (binding.binding) set.add(binding.binding);
    });

    this.hotkey.accelerators = set;
  }

}
</script>

<style lang="less" scoped>
.Hotkey {
  display: flex;
  flex-direction: row;
}

.Hotkey-description {
  width: 200px;
  padding-right: 10px;
}

.Hotkey-input {
  display: inline-block;
  width: 150px;
}

.Hotkey-control {
  margin-left: 15px;
  cursor: pointer;
  opacity: 0.6;

  &:hover {
    opacity: 1.0;
  }
}

.bindings-enter-active, .bindings-leave-active {
  transition: all 0.2s;
}

.bindings-enter, .bindings-leave-to {
  opacity: 0;
  transform: scale(1, 0);
}
</style>

// app/components-react/windows/settings/Hotkey.tsx
import React, { useState, useEffect, KeyboardEvent, MouseEvent, UIEvent } from 'react';
import { IHotkey, IBinding } from 'services/hotkeys';
import cx from 'classnames';
import styles from './Hotkey.m.less';
import HotkeyBinding from 'components-react/shared/HotkeyBinding';

/**
 * Represents a binding that has a unique key for CSS animations
 */
interface IKeyedBinding {
  binding: IBinding;
  key: string;
}

interface HotkeyProps {
  hotkey: IHotkey;
}

// This is kind of weird, but the key attribute allows
// us to uniquely identify that binding in the DOM,
// which allows CSS animations to work properly.
function createBindingWithKey(binding: IBinding): IKeyedBinding {
  return {
    binding,
    key: Math.random().toString(36).substring(2, 15),
  };
}

function getBlankBinding() {
  return {
    key: '',
    modifiers: {
      alt: false,
      ctrl: false,
      shift: false,
      meta: false,
    },
  };
}

function addEmptyBindingAt(index: number) {
  return (bindings: IKeyedBinding[]) => {
    const newBindings = [...bindings];
    newBindings.splice(index + 1, 0, createBindingWithKey(getBlankBinding()));
    return newBindings;
  };
}

function removeBindingAt(index: number) {
  return (bindings: IKeyedBinding[]) => {
    const newBindings = [...bindings];
    // If this is the last binding, replace it with an
    // empty binding instead.
    if (newBindings.length === 1) {
      newBindings[0].binding = getBlankBinding();
    } else {
      newBindings.splice(index, 1);
    }

    return newBindings;
  };
}

function setBindingAtIndex(index: number, binding: IBinding) {
  return (bindings: IKeyedBinding[]) => {
    const newBindings = [...bindings];
    newBindings.splice(index, 1, createBindingWithKey(binding));
    return newBindings;
  };
}

export default function Hotkey(props: HotkeyProps) {
  const { hotkey } = props;

  const [bindings, setBindings] = useState<IKeyedBinding[]>(() => {
    // Create a blank binding if there are no bindings
    const initialBindings = hotkey.bindings.length ? hotkey.bindings : [getBlankBinding()];

    return initialBindings.map(createBindingWithKey);
  });

  /**
   * Adds a new blank binding
   */
  function addBinding(index: number) {
    return setBindings(addEmptyBindingAt(index));
  }

  function removeBinding(index: number) {
    return setBindings(removeBindingAt(index));
  }

  // TODO: can we possibly avoid mutation in the future?
  useEffect(() => {
    hotkey.bindings = bindings.map(b => b.binding);
  }, [bindings]);

  function HotkeyBindings({ bindings }: { bindings: IKeyedBinding[] }) {
    const setBinding = (index: number, binding: IBinding) => {
      setBindings(setBindingAtIndex(index, binding)(bindings));
    };

    return (
      <div className={styles.hotkeyBindings}>
        {bindings.map((binding, index) => (
          <div key={binding.key} className={styles.hotkeyBinding}>
            <HotkeyBinding
              hotkey={hotkey}
              binding={binding.binding}
              onBind={(binding: IBinding) => {
                setBinding(index, binding);
              }}
            />
            <div className={styles.hotkeyControls}>
              <i
                data-testid="add-binding"
                className={cx(styles.hotkeyControl, 'fa', 'fa-plus')}
                onClick={() => addBinding(index)}
              />
              <i
                data-testid="remove-binding"
                className={cx(styles.hotkeyControl, 'fa', 'fa-minus')}
                onClick={() => removeBinding(index)}
              />
            </div>
          </div>
        ))}
      </div>
    );
  }

  const description = hotkey.description || '';
  const testId = description.replace(/\s+/, '_');

  return (
    <div className={styles.hotkey} data-testid={testId}>
      <HotkeyBindings bindings={bindings} />
    </div>
  );
}
