// app/components/InstalledApps.vue
<template>
  <div class="section">
    <table>
      <thead>
        <tr>
          <th> {{ $t('Icon') }} </th>
          <th> {{ $t('Name')}} </th>
          <th> {{ $t('Vers')}} </th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="app in installedApps"
          :key="app.id"
        >
          <td> <img :src="app.icon" alt="-" width='50'> </td>
          <td> {{ app.manifest.name }} </td>
          <td> {{ app.manifest.version }} </td>
          <td class="button-container button-container--right">
            <button
              v-if="isEnabled(app.id)"
              @click="reload(app.id)"
              class="button button--trans"><i class="icon-reset"></i>{{ $t('Reload') }}</button>
            <button
              v-if="noUnpackedVersionLoaded(app.id)"
              @click="toggleEnable(app)"
              class="button"
              :class="{ 'button--soft-warning': isEnabled(app.id), 'button--default': !isEnabled(app.id) }">
              {{ isEnabled(app.id) ? 'Disable' : 'Enable' }}
            </button>
            <div v-else>
              <button
                disabled
                class="button button--default">
                {{ $t('Unpacked vers loaded') }}
              </button>
              <i
                v-tooltip.left=" $t('You must unload unpacked version before enabling this app.') "
                class="icon-question"
              />
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script lang="ts" src="./InstalledApps.vue.ts"></script>

<style lang="less" scoped>
table td:last-child {
  text-align: right;
}

.button-container {
  .button {
    margin-right: 0;
  }
}
</style>

// app/components-react/windows/settings/InstalledApps.tsx
import React from 'react';
import { Tooltip } from 'antd';
import cx from 'classnames';
import { Services } from 'components-react/service-provider';
import { ILoadedApp } from 'services/platform-apps';
import { $t } from 'services/i18n';
import styles from './InstalledApps.m.less';
import { useVuex } from 'components-react/hooks';

export default function InstalledApps() {
  const { PlatformAppsService } = Services;

  const { installedApps } = useVuex(() => ({
    installedApps: PlatformAppsService.views.productionApps,
  }));
  const enabledInstalledAppIds = installedApps.filter(app => app.enabled).map(app => app.id);

  function isEnabled(appId: string) {
    return enabledInstalledAppIds.includes(appId);
  }

  function reload(appId: string) {
    PlatformAppsService.actions.refreshApp(appId);
  }

  function toggleEnable(app: ILoadedApp) {
    if (isEnabled(app.id)) {
      PlatformAppsService.actions.setEnabled(app.id, false);
    } else {
      PlatformAppsService.actions.setEnabled(app.id, true);
    }
  }

  function noUnpackedVersionLoaded(appId: string) {
    return !PlatformAppsService.views.enabledApps.find(app => app.id === appId && app.unpacked);
  }

  return (
    <div className="section">
      <table className={styles.installedApps} style={{ width: '100%' }}>
        <thead>
          <tr>
            <th> {$t('Icon')} </th>
            <th> {$t('Name')} </th>
            <th> {$t('Vers')} </th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {installedApps.map(app => (
            <tr key={app.id}>
              <td>
                {' '}
                <img src={app.icon} alt="-" width="50" />{' '}
              </td>
              <td> {app.manifest.name} </td>
              <td> {app.manifest.version} </td>
              <td className={cx(styles.buttonContainer, 'button-container--right')}>
                {isEnabled(app.id) && (
                  <button onClick={() => reload(app.id)} className="button button--trans">
                    <i className="icon-reset"></i>
                    {$t('Reload')}
                  </button>
                )}
                {noUnpackedVersionLoaded(app.id) && (
                  <button
                    onClick={() => toggleEnable(app)}
                    className={cx('button', {
                      'button--soft-warning': isEnabled(app.id),
                      'button--default': !isEnabled(app.id),
                    })}
                  >
                    {isEnabled(app.id) ? $t('Disable') : $t('Enable')}
                  </button>
                )}
                {!isEnabled(app.id) && !noUnpackedVersionLoaded(app.id) && (
                  <>
                    <button disabled className="button button--default">
                      {$t('Unpacked vers loaded')}
                    </button>
                    <Tooltip
                      title={$t('You must unload unpacked version before enabling this app.')}
                      placement="left"
                    >
                      <i className="icon-question" />
                    </Tooltip>
                  </>
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
