// app/components-react/shared/inputs/TextInput.tsx
import { ITextMetadata } from '../../../components/shared/inputs';
import styles from '../../../components/shared/inputs/TextInput.m.less';
import React from 'react';
import cx from 'classnames';

type ITextInputProps = ITextMetadata & { value: string };

export function TextInput(props: ITextInputProps) {
  return (
    <span
      className={cx(styles.textInput, {
        [styles.fullWidth]: this.metadata.fullWidth,
        [styles.disabled]: this.metadata.disabled,
      })}
      data-role="input"
      data-type="text"
      data-name={this.options.name}
      data-title={this.options.title}
    >
      {this.options.icon && <i class={`fa fa-${this.options.icon}`} />}
      <input
        type={this.textVisible ? 'text' : 'password'}
        placeholder={this.options.placeholder}
        value={this.value}
        onInput={(e: { target: { value: string } }) => this.handleInput(e.target.value)}
        onChange={(e: { target: { value: string } }) => this.handleChange(e.target.value)}
        name={this.options.uuid}
        v-validate={this.validate}
        disabled={this.options.disabled}
        onFocus={() => this.$emit('focus')}
        onBlur={() => this.$emit('blur')}
      />
      {this.toggleVisibleButton}
      {this.$slots.default}
    </span>
  );
}

// app/components/shared/inputs/TextInput.vue
<template>
  <span
    :class="{ 'text-input': true, 'full-width': metadata.fullWidth }"
    data-role="input"
    data-type="text"
    :data-name="options.name"
  >
    <input
        :type="textVisible ? 'text' : 'password'"
        :placeholder="options.placeholder"
        :value="value"
        @input="emitInput($event.target.value)"
        :name="uuid"
        v-validate="validate"
        :disabled="metadata.disabled"
    />
    <button
      class="button button--input button--default"
      v-if="metadata.masked"
      @click="toggleVisible">
      {{ textVisible ? $t('Hide') : $t('Show') }}
    </button>
  </span>
</template>

<script lang="ts" src="./TextInput.vue.ts"></script>

<style lang="less" scoped>
  @import "../../../styles/index";

  .text-input {
    position: relative;
    display: flex;
  }

  .text-input.full-width {
    width: 100%
  }

  .button--input {
    flex: 0 0 auto;
    width: 80px;
    margin-left: 12px;
  }
</style>
