// app/components-react/windows/Notifications.tsx
import React, { useEffect } from 'react';
import moment from 'moment';
import cx from 'classnames';
import { useRenderInterval, useVuex } from 'components-react/hooks';
import { ModalLayout } from 'components-react/shared/ModalLayout';
import { Services } from 'components-react/service-provider';
import { INotification } from 'services/notifications';
import { $t } from 'services/i18n';
import styles from './Notifications.m.less';

export default function Notifications() {
  const { NotificationsService } = Services;

  useRenderInterval(() => {}, 60 * 1000);
  useEffect(() => () => NotificationsService.actions.markAllAsRead(), []);

  const { notificationGroups, notificationsCount } = useVuex(() => ({
    notificationGroups: {
      unread: NotificationsService.views.getUnread(),
      read: NotificationsService.views.getRead(),
    },
    notificationsCount: NotificationsService.views.getAll().length,
  }));

  function onNotificationClickHandler(id: number) {
    NotificationsService.actions.applyAction(id);
  }

  function momentize(time: number): string {
    return moment(time).fromNow();
  }

  return (
    <ModalLayout hideFooter>
      {!notificationsCount && <h4>{$t("You don't have any notifications")}</h4>}

      {Object.keys(notificationGroups).map((groupName: string) => (
        <div key={groupName}>
          {notificationGroups[groupName].length > 0 && (
            <h4>{groupName === 'unread' ? $t('New Notifications') : $t('Log')}</h4>
          )}
          {notificationGroups[groupName].map((notify: INotification) => (
            <div
              key={notify.id}
              onClick={() => onNotificationClickHandler(notify.id)}
              className={cx(styles.notification, {
                [styles.unread]: notify.unread,
                [styles.hasAction]: notify.action,
              })}
              data-name={notify.action && 'hasAction'}
            >
              <div className="icon">
                {notify.type === 'INFO' && <span className="fa fa-info-circle" />}
                {notify.type === 'WARNING' && <span className="fa fa-warning" />}
              </div>
              <div className="message">{notify.message}</div>
              <div className={styles.date}>{momentize(notify.date)}</div>
            </div>
          ))}
        </div>
      ))}
    </ModalLayout>
  );
}

// app/components/windows/Notifications.vue
<template>
<modal-layout :showControls="false">
  <div slot="content">

    <h4 v-if="!notificationsCount">
      {{ $t('You don\'t have any notifications') }}
    </h4>

    <div v-for="(notificationsService, groupName) in notificationGroups" :key="groupName">
      <h4 v-if="notificationsService.length">
        {{ groupName === 'unread' ? $t('New Notifications') : $t('Log') }}
      </h4>
      <div
        class="notification"
        v-for="notify in notificationsService"
        :key="notify.id"
        @click="onNotificationClickHandler(notify.id)"
        :class = "{
          'unread': notify.unread,
          'has-action': notify.action
        }"
      >
        <div class="icon">
          <span class="fa fa-info-circle" v-if="notify.type == 'INFO'"></span>
          <span class="fa fa-warning" v-if="notify.type == 'WARNING'"></span>
        </div>
        <div class="message">{{ notify.message }}</div>
        <div class="date">{{ moment(notify.date) }}</div>

      </div>
    </div>
  </div>

</modal-layout>
</template>

<script lang="ts" src="./Notifications.vue.ts"></script>

<style lang="less" scoped>
@import "../../styles/index";

.notification {
  color: var(--icon);
  padding: 5px 10px;
  margin-bottom: 5px;
  display: grid;
  grid-template-columns: 30px 1fr 130px;
  background: var(--hover);
  .border();

  &.has-action:hover {
    color: var(--title);
    background: var(--section);
    cursor: pointer;
  }

  &:last-child {
    margin-bottom: 20px;
  }

  .fa-warning {
    color: var(--warning);
  }

  .date {
    text-align: right;
  }
}
</style>
